server {
  listen 80;
  server_name iboluo.top blog.iboluo.top;

  server_tokens off;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type text/plain;
    try_files $uri =404;
  }

  location / {
    return 301 https://iboluo.top$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name iboluo.top;

  server_tokens off;
  ssl_certificate /etc/letsencrypt/live/iboluo.top/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/iboluo.top/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;

  root /usr/share/nginx/blog;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~* \\.(?:css|js|gif|png|jpg|jpeg|webp|svg|ico|woff|woff2)$ {
    expires 7d;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }
}

server {
  listen 443 ssl;
  server_name blog.iboluo.top;

  server_tokens off;
  ssl_certificate /etc/letsencrypt/live/iboluo.top/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/iboluo.top/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;

  return 301 https://iboluo.top$request_uri;
}
